# Generated by Django 5.2.17 on 2026-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_character_avatar_character_memories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='auto_mode',
            field=models.CharField(default='parallel', max_length=8),
        ),
    ]

