# Generated by Django 5.2.17 on 2026-09-18 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conversation_auto_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='generationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'queued')), fields=('conversation',), name='one_queued_generation_per_conversation'),
        ),
    ]

