# Generated by Django 5.2.17 on 2026-09-20 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('thought', '内心想法'), ('dialogue', '台词'), ('action', '动作'), ('ooc', '导演'), ('narration', '旁白'), ('state', '状态')], max_length=16),
        ),
        migrations.CreateModel(
            name='Worldbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorldbookCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.worldbookcategory')),
                ('worldbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.worldbook')),
            ],
            options={
                'ordering': ['position', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorldbookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('trigger_mode', models.CharField(choices=[('keyword', '关键词'), ('always', '始终'), ('manual', '手动')], default='keyword', max_length=12)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('insertion_position', models.CharField(choices=[('before_character', '角色卡前'), ('after_character', '角色卡后'), ('before_recent_messages', '最近对话前')], default='before_character', max_length=24)),
                ('priority', models.IntegerField(default=0)),
                ('scope_type', models.CharField(choices=[('global', '全局'), ('character', '指定角色'), ('conversation', '指定对话')], default='global', max_length=16)),
                ('import_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='entries', to='core.worldbookcategory')),
                ('scoped_characters', models.ManyToManyField(blank=True, related_name='scoped_worldbook_entries', to='core.character')),
                ('scoped_conversations', models.ManyToManyField(blank=True, related_name='scoped_worldbook_entries', to='core.conversation')),
                ('worldbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.worldbook')),
            ],
            options={
                'ordering': ['insertion_position', '-priority', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConversationWorldbookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worldbook_config', to='core.conversation')),
                ('enabled_worldbooks', models.ManyToManyField(blank=True, related_name='enabled_in_conversations', to='core.worldbook')),
                ('enabled_categories', models.ManyToManyField(blank=True, related_name='enabled_in_conversations', to='core.worldbookcategory')),
                ('excluded_categories', models.ManyToManyField(blank=True, related_name='excluded_in_conversations', to='core.worldbookcategory')),
                ('excluded_entries', models.ManyToManyField(blank=True, related_name='excluded_in_conversations', to='core.worldbookentry')),
                ('manual_entries', models.ManyToManyField(blank=True, related_name='manually_enabled_in_conversations', to='core.worldbookentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='worldbook',
            index=models.Index(fields=['owner', 'enabled'], name='worldbook_owner_enabled_idx'),
        ),
        migrations.AddConstraint(
            model_name='worldbook',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_worldbook_name'),
        ),
        migrations.AddIndex(
            model_name='worldbookcategory',
            index=models.Index(fields=['worldbook', 'parent', 'position'], name='worldbook_category_tree_idx'),
        ),
        migrations.AddConstraint(
            model_name='worldbookcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('worldbook', 'parent', 'name'), name='unique_worldbook_category_sibling_name'),
        ),
        migrations.AddConstraint(
            model_name='worldbookcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('worldbook', 'name'), name='unique_worldbook_root_category_name'),
        ),
        migrations.AddIndex(
            model_name='worldbookentry',
            index=models.Index(fields=['worldbook', 'enabled', 'trigger_mode'], name='worldbook_entry_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='worldbookentry',
            constraint=models.UniqueConstraint(fields=('worldbook', 'name'), name='unique_worldbook_entry_name'),
        ),
        migrations.AddConstraint(
            model_name='worldbookentry',
            constraint=models.CheckConstraint(condition=models.Q(('trigger_mode__in', ['keyword', 'always', 'manual'])), name='valid_worldbook_trigger_mode'),
        ),
        migrations.AddConstraint(
            model_name='worldbookentry',
            constraint=models.CheckConstraint(condition=models.Q(('insertion_position__in', ['before_character', 'after_character', 'before_recent_messages'])), name='valid_worldbook_insertion_position'),
        ),
        migrations.AddConstraint(
            model_name='worldbookentry',
            constraint=models.CheckConstraint(condition=models.Q(('scope_type__in', ['global', 'character', 'conversation'])), name='valid_worldbook_scope_type'),
        ),
    ]

