# Generated by Django 5.2.17 on 2026-09-20 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_worldbook_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='affinity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='clothing_state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='clothing_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='CharacterCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('characters', models.ManyToManyField(blank=True, related_name='categories', to='core.character')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.charactercategory')),
            ],
            options={
                'ordering': ['position', 'name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'parent', 'name'), name='unique_character_category_sibling')],
            },
        ),
    ]

