# Generated by Django 5.2.17 on 2026-09-28 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_registration_policy_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_key', models.CharField(choices=[('main_154', '总站 154'), ('main_123', '总站 123')], max_length=32, unique=True)),
                ('site_id', models.UUIDField(unique=True)),
                ('central_url', models.URLField(max_length=500)),
                ('central_public_key', models.CharField(max_length=43)),
                ('private_key_env_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('paired_at', models.DateTimeField(auto_now_add=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SiteCommandReceipt',
            fields=[
                ('command_id', models.UUIDField(primary_key=True, serialize=False)),
                ('payload_digest', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=12)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.UUIDField()),
                ('source_message_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('upsert', '新增或更新'), ('delete', '删除')], default='upsert', max_length=8)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'next_attempt_at', 'id'], name='chat_outbox_pending_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDirectoryOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.UUIDField()),
                ('source_user_id', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'next_attempt_at', 'id'], name='user_dir_outbox_pending_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=12)),
                ('was_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposition', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_warnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
