# Generated by Django 5.2.17 on 2026-09-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_federationidentity_sitecommandreceipt_chatsyncoutbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwarning',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
