# Generated by Django 5.2.17 on 2026-10-08 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userwarning_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='story_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='story_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConversationActorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_snapshot', models.JSONField(default=dict)),
                ('state_fields', models.JSONField(default=dict)),
                ('relationship_notes', models.JSONField(default=dict)),
                ('affinity', models.PositiveSmallIntegerField(default=0)),
                ('clothing_type', models.CharField(blank=True, max_length=200)),
                ('clothing_state', models.CharField(blank=True, max_length=200)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('initialization_source', models.CharField(default='角色卡初始设定', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_states', to='core.character')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_states', to='core.conversation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'character'), name='unique_story_actor_state')],
            },
        ),
    ]
