# Generated by Django 5.2.17 on 2026-10-08 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_initialize_story_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='locked_facts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conversation',
            name='memory_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='memory_summary_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='memory_summary_status',
            field=models.CharField(default='idle', max_length=12),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='task_kind',
            field=models.CharField(default='dialogue', max_length=12),
        ),
        migrations.CreateModel(
            name='StoryMemoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('locked_facts', models.JSONField(default=list)),
                ('source', models.CharField(max_length=20)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_history', to='core.conversation')),
            ],
            options={
                'ordering': ['-revision'],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'revision'), name='unique_story_memory_revision')],
            },
        ),
    ]
