# Generated by Django 5.2.17 on 2026-10-08 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_story_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='story_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='StoryCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='core.conversation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
