# Generated by Django 5.2.17 on 2026-10-08 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_story_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alternate_greetings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='character',
            name='character_worldbook',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='character',
            name='first_mes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='lore_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='character',
            name='personal_worldbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_character_cards', to='core.worldbook'),
        ),
        migrations.AddField(
            model_name='character',
            name='scenario',
            field=models.TextField(blank=True),
        ),
    ]
