# Generated by Django 5.2.17 on 2026-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_complete_character_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='context_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
