# Generated by Django 5.2.17 on 2026-10-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_character_context_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSettingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_field', models.CharField(max_length=30)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_segments', to='core.character')),
            ],
            options={
                'ordering': ['source_field', 'start'],
                'constraints': [models.UniqueConstraint(fields=('character', 'source_field', 'start', 'end'), name='unique_character_source_segment')],
            },
        ),
    ]
