# Generated by Django 5.2.17 on 2026-10-08 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_charactersettingsegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=250)),
                ('source', models.TextField()),
                ('source_hash', models.CharField(max_length=64)),
                ('options', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.importtask')),
            ],
        ),
        migrations.CreateModel(
            name='ImportSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('status', models.CharField(default='queued', max_length=20)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=120)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('raw_output', models.TextField(blank=True)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.importtask')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('task', 'index'), name='unique_import_task_segment')],
            },
        ),
    ]
