# Generated by Django 5.2.17 on 2026-10-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_importtask_importtaskevent_importsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='lease_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
