# Generated by Django 5.2.17 on 2026-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_generationjob_lease_token_generationjob_lease_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='coverage_reviews',
            field=models.JSONField(default=dict),
        ),
    ]
