# Generated by Django 5.2.17 on 2026-10-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_importtask_coverage_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescans', to='core.importtask'),
        ),
        migrations.AddField(
            model_name='importtask',
            name='source_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importtask',
            name='source_start',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
