# Generated by Django 5.2.17 on 2026-10-08 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_importtask_parent_importtask_source_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_objects', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('undo_result', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.importtask')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='unique_import_batch_key')],
            },
        ),
    ]
