# Generated by Django 5.2.17 on 2026-10-08 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_importbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationContextTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected', models.JSONField(default=list)),
                ('excluded', models.JSONField(default=list)),
                ('estimated_usage', models.JSONField(default=dict)),
                ('configuration', models.JSONField(default=dict)),
                ('character_snapshot', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.character')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_traces', to='core.generationjob')),
            ],
        ),
    ]
