# Generated by Django 5.2.17 on 2026-10-08 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_personalbackupjob_personalrestorereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='context_trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.generationcontexttrace'),
        ),
    ]
