# Generated by Django 5.2.17 on 2026-10-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_message_context_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='generation_configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
