# Generated by Django 5.2.17 on 2026-09-24 11:46

from django.db import migrations, models


def seed_lease_state(apps, schema_editor):
    LeaseState = apps.get_model("witness_core", "LeaseState")
    LeaseState.objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('holder_id', models.CharField(blank=True, default='', max_length=64)),
                ('epoch', models.PositiveBigIntegerField(default=0)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'witness_lease_state',
            },
        ),
        migrations.CreateModel(
            name='RequestNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('request_id', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'witness_request_nonce',
                'constraints': [models.UniqueConstraint(fields=('node_id', 'request_id'), name='unique_witness_node_request')],
            },
        ),
        migrations.RunPython(seed_lease_state, migrations.RunPython.noop),
    ]
